import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import request from "../utils/request";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*  Header */}

      <Header />

      {/* Navbar */}

      <Navbar />

      {/* Results */}

      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre || "fetchTrending";
  const requests = await (
    await fetch(`
  https://api.themoviedb.org/3${request[genre].url}
  `)
  ).json();
  return {
    props: {
      results: requests.results,
    },
  };
}
